server.port=${PORT:8090}
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,application/json

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=604800

supabase.url=${SUPABASE_URL:https://pvwcpowcsstdcvcghjff.supabase.co}
supabase.key=${SUPABASE_KEY:sb_secret_NvQiIbELqA7FGe9W6wq8YA_yAxTiQf0}
admin.emails=${ADMIN_EMAILS:teuye144@dgsw.hs.kr}
google.client-id=362966934345-chc1dngqgtifsh0cegqvsvv4v4v7hb50.apps.googleusercontent.com
app.self-url=${RENDER_EXTERNAL_URL:http://localhost:8090}
